package com.rado.app.api;

import org.json.simple.JSONObject;

public class RawStatsDto
{
	public long gold;
	public long magicDamageDealtToChampions;
	public long largestMultiKill;
	public long totalDamageDealtToBuildings;
	public long teamObjective;
	public long trueDamageDealtPlayer;
	public long tripleKills;
	public long nodeNeutralizeAssist;
	public long playerScore0;
	public long playerScore1;
	public long playerScore2;
	public long playerScore3;
	public long playerScore4;
	public long playerScore5;
	public long playerScore6;
	public long playerScore7;
	public long playerScore8;
	public long playerScore9;
	public long totalScoreRank;
	public long neutralMinionsKilled;
	public long playerRole;
	public long physicalDamageDealtToChampions;
	public long level;
	public long numItemsBought;
	public long nodeCapture;
	public long turretsKilled;
	public long totalUnitsHealed;
	public long team;
	public long totalDamageTaken;
	public long victoryPolongTotal;
	public long visionWardsBought;
	public long largestCriticalStrike;
	public long firstBlood;
	public long largestKillingSpree;
	public long quadraKills;
	public long magicDamageTaken;
	public long item0;
	public long item1;
	public long item2;
	public long item3;
	public long item4;
	public long item5;
	public long item6;
	public long neutralMinionsKilledYourJungle;
	public long timePlayed;
	public boolean nexusKilled;
	public long trueDamageTaken;
	public long nodeNuetralize;
	public long damageDealtPlayer;
	public long assists;
	public long spell1Cast;
	public long goldSpent;
	public long totalTimeCrowdControlDealt;
	public long minionsDenied;
	public long totalDamageDealtToChampions;
	public long spell3Cast;
	public long physicalDamageTaken;
	public long totalPlayerScore;
	public boolean win;
	public long objectivePlayerScore;
	public long totalDamageDealt;
	public long playerPosition;
	public long spell4Cast;
	public long bountyLevel;
	public long neutralMinionsKilledEnemyJungle;
	public long spell2Cast;
	public long sightWardsBought;
	public long championsKilled;
	public long trueDamageDealtToChampions;
	public long summonSpell1Cast;
	public long physicalDamageDealtPlayer;
	public long goldEarned;
	public long superMonstersKilled;
	public long killingSprees;
	public long unrealKills;
	public long wardPlaced;
	public long barracksKilled;
	public long wardKilled;
	public long consumablesPurchased;
	public long legendaryItemsCreated;
	public long minionsKilled;
	public long itemsPurchased;
	public long doubleKills;
	public long nodeCaptureAssist;
	public long summonSpell2Cast;
	public long combatPlayerScore;
	public long pentaKills;
	public long totalHeal;
	public long numDeaths;
	public long magicDamageDealtPlayer;

	public RawStatsDto(JSONObject stats)
	{
		gold = (long) stats.get("gold");
		magicDamageDealtToChampions = (long) stats.get("magicDamageDealtToChampions");
		largestMultiKill = (long) stats.get("largestMultiKill");
		totalDamageDealtToBuildings = (long) stats.get("totalDamageDealtToBuildings");
		teamObjective = (long) stats.get("teamObjective");
		trueDamageDealtPlayer = (long) stats.get("trueDamageDealtPlayer");
		tripleKills = (long) stats.get("tripleKills");
		nodeNeutralizeAssist = (long) stats.get("nodeNeutralizeAssist");
		playerScore0 = (long) stats.get("playerScore0");
		playerScore1 = (long) stats.get("playerScore1");
		playerScore2 = (long) stats.get("playerScore2");
		playerScore3 = (long) stats.get("playerScore3");
		playerScore4 = (long) stats.get("playerScore4");
		playerScore5 = (long) stats.get("playerScore5");
		playerScore6 = (long) stats.get("playerScore6");
		playerScore7 = (long) stats.get("playerScore7");
		playerScore8 = (long) stats.get("playerScore8");
		playerScore9 = (long) stats.get("playerScore9");
		totalScoreRank = (long) stats.get("totalScoreRank");
		neutralMinionsKilled = (long) stats.get("neutralMinionsKilled");
		playerRole = (long) stats.get("playerRole");
		physicalDamageDealtToChampions = (long) stats.get("physicalDamageDealtToChampions");
		level = (long) stats.get("level");
		numItemsBought = (long) stats.get("numItemsBought");
		nodeCapture = (long) stats.get("nodeCapture");
		turretsKilled = (long) stats.get("turretsKilled");
		totalUnitsHealed = (long) stats.get("totalUnitsHealed");
		team = (long) stats.get("team");
		totalDamageTaken = (long) stats.get("totalDamageTaken");
		victoryPolongTotal = (long) stats.get("victoryPolongTotal");
		visionWardsBought = (long) stats.get("visionWardsBought");
		largestCriticalStrike = (long) stats.get("largestCriticalStrike");
		firstBlood = (long) stats.get("firstBlood");
		largestKillingSpree = (long) stats.get("largestKillingSpree");
		quadraKills = (long) stats.get("quadraKills");
		magicDamageTaken = (long) stats.get("magicDamageTaken");
		item0 = (long) stats.get("item0");
		item1 = (long) stats.get("item1");
		item2 = (long) stats.get("item2");
		item3 = (long) stats.get("item3");
		item4 = (long) stats.get("item4");
		item5 = (long) stats.get("item5");
		item6 = (long) stats.get("item6");
		neutralMinionsKilledYourJungle = (long) stats.get("neutralMinionsKilledYourJungle");
		timePlayed = (long) stats.get("timePlayed");
		nexusKilled = (boolean) stats.get("nexusKilled");
		trueDamageTaken = (long) stats.get("trueDamageTaken");
		nodeNuetralize = (long) stats.get("nodeNuetralize");
		damageDealtPlayer = (long) stats.get("damageDealtPlayer");
		assists = (long) stats.get("assists");
		spell1Cast = (long) stats.get("spell1Cast");
		goldSpent = (long) stats.get("goldSpent");
		totalTimeCrowdControlDealt = (long) stats.get("totalTimeCrowdControlDealt");
		minionsDenied = (long) stats.get("minionsDenied");
		totalDamageDealtToChampions = (long) stats.get("totalDamageDealtToChampions");
		spell3Cast = (long) stats.get("spell3Cast");
		physicalDamageTaken = (long) stats.get("physicalDamageTaken");
		totalPlayerScore = (long) stats.get("totalPlayerScore");
		win = (boolean) stats.get("win");
		objectivePlayerScore = (long) stats.get("objectivePlayerScore");
		totalDamageDealt = (long) stats.get("totalDamageDealt");
		playerPosition = (long) stats.get("playerPosition");
		spell4Cast = (long) stats.get("spell4Cast");
		bountyLevel = (long) stats.get("bountyLevel");
		neutralMinionsKilledEnemyJungle = (long) stats.get("neutralMinionsKilledEnemyJungle");
		spell2Cast = (long) stats.get("spell2Cast");
		sightWardsBought = (long) stats.get("sightWardsBought");
		championsKilled = (long) stats.get("championsKilled");
		trueDamageDealtToChampions = (long) stats.get("trueDamageDealtToChampions");
		summonSpell1Cast = (long) stats.get("summonSpell1Cast");
		physicalDamageDealtPlayer = (long) stats.get("physicalDamageDealtPlayer");
		goldEarned = (long) stats.get("goldEarned");
		superMonstersKilled = (long) stats.get("superMonstersKilled");
		killingSprees = (long) stats.get("killingSprees");
		unrealKills = (long) stats.get("unrealKills");
		wardPlaced = (long) stats.get("wardPlaced");
		barracksKilled = (long) stats.get("barracksKilled");
		wardKilled = (long) stats.get("wardKilled");
		consumablesPurchased = (long) stats.get("consumablesPurchased");
		legendaryItemsCreated = (long) stats.get("legendaryItemsCreated");
		minionsKilled = (long) stats.get("minionsKilled");
		itemsPurchased = (long) stats.get("itemsPurchased");
		doubleKills = (long) stats.get("doubleKills");
		nodeCaptureAssist = (long) stats.get("nodeCaptureAssist");
		summonSpell2Cast = (long) stats.get("summonSpell2Cast");
		combatPlayerScore = (long) stats.get("combatPlayerScore");
		pentaKills = (long) stats.get("pentaKills");
		totalHeal = (long) stats.get("totalHeal");
		numDeaths = (long) stats.get("numDeaths");
		magicDamageDealtPlayer = (long) stats.get("magicDamageDealtPlayer");
	}
}
